### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by fuyuhin** [Kumhy/XuanFengEx#1]

**Comment by fuyuhin** [comment]
magnet:?xt=urn:btih:ddb75d0c5672b96a280a25b8d3d68a27d0dc9e94&dn=Sully.2016.720p.BluRay.x264-SPARKS&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710

**Comment by Kumhy** [comment]
http://lixian.qq.com/handler/lixian/get_http_url.php
已经取不到文件真实地址了，旋风最近在抽风。
